X_tru_ixt___ = cell(n_i,1);
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
index_nt_from_nj_ = index_nt_from_nj_i__{1+ni};
ignore_Y_tru_xj__ = ignore_Y_tru_ixj___{1+ni};
Y_tru_xj__ = Y_tru_ixj___{1+ni};
X_tru_xt__ = zeros(n_x,n_t);
X_tru_xt__(:,1+index_nt_from_nj_) = 0.5*Y_tru_xj__.*(~ignore_Y_tru_xj__).*( isfinite(Y_tru_xj__));
X_tru_xt__(find(~isfinite(X_tru_xt__))) = 0;
X_tru_ixt___{1+ni} = X_tru_xt__;
clear n_t t_t_ X_tru_xt__ index_nt_from_nj_ ignore_Y_tru_xj__ Y_tru_xj__ ;
end;%for ni=0:n_i-1;

ni = 44;
SDE_nlp_jXYC_strip_2( ...
 n_x ...
,n_t_i_(1+ni) ...
,X_tru_ixt___{1+ni} ...
,n_j_i_(1+ni) ...
,index_nt_from_nj_i__{1+ni} ...
,ignore_Y_tru_ixj___{1+ni} ...
,Y_tru_ixj___{1+ni} ...
,C_omega ...
,C_l0 ...
,C_l1 ...
),;
