function ...
[ ...
 Q_xt__ ...
] = ...
PAD_Q_ta_strip_0( ...
 n_t ...
,t_t_ ...
,n_x ...
,n_a ...
,a_xa__ ...
);

str_thisfunction = 'PAD_Q_ta_strip_0';

if (nargin<1);
disp(sprintf(' %% testing %s',str_thisfunction));
%%%%%%%%;
rng(1);
tolerance_master = 1e-6;
T_max = 64;
n_x = 2;
n_a = 3;
a_xa__ = [ +1.00 , -1.00/T_max , +0.50/T_max.^2   ; ...
	   -0.50 , +0.25/T_max , -0.25/T_max.^2 ] ;
n_t = 1024*8;
t_t_ = linspace(0,T_max,n_t);
[ ...
 Q_xt__ ...
] = ...
PAD_Q_ta_strip_0( ...
 n_t ...
,t_t_ ...
,n_x ...
,n_a ...
,a_xa__ ...
);
plot(t_t_,Q_xt__,'-');
xlim([0,T_max]); xlabel('t_t_','Interpreter','none');
ylabel('Q_xt__','Interpreter','none');
%%%%%%%%;
disp('returning'); return;
end;%if (nargin<1);

na=0;
if (nargin<1+na); n_t=[]; end; na=na+1;
if (nargin<1+na); t_t_=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); n_a=[]; end; na=na+1;
if (nargin<1+na); a_xa__=[]; end; na=na+1;

Q_xt__ = a_xa__*bsxfun(@power,reshape(t_t_,[1,n_t]),reshape(0:n_a-1,[n_a,1]));

