function ...
[ ...
 nlp_tXYC ...
,CtCn_xx__ ...
] = ...
PAD_nlp_tXYC_strip_1( ...
 n_x ...
,n_t ...
,X_xt__ ...
,ignore_Y_xt__ ...
,Y_xt__ ...
,C_omega ...
,C_l0 ...
,C_l1 ...
);

na=0;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); n_t=[]; end; na=na+1;
if (nargin<1+na); X_xt__=[]; end; na=na+1;
if (nargin<1+na); ignore_Y_xt__=[]; end; na=na+1;
if (nargin<1+na); Y_xt__=[]; end; na=na+1;
if (nargin<1+na); C_omega=[]; end; na=na+1;
if (nargin<1+na); C_l0=[]; end; na=na+1;
if (nargin<1+na); C_l1=[]; end; na=na+1;

[ ...
 ~ ...
,CtCn_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,C_omega ...
,C_l0 ...
,C_l1 ...
);
[Z2_base_0,l2_stretch_0] = PAD_missing_2d_integral_helper_0(0,C_omega,C_l0,C_l1); %<-- ignore XY_(1+0) ;
[Z2_base_1,l2_stretch_1] = PAD_missing_2d_integral_helper_0(1,C_omega,C_l0,C_l1); %<-- ignore XY_(1+1) ;

if isempty(ignore_Y_xt__); ignore_Y_xt__ = ~isfinite(Y_xt__); end;%if isempty(ignore_Y_xt__); 
%%%%;
XY_xt__ = Y_xt__ - X_xt__;
%%%%%%%%;
% vectorize this later. ;
%%%%%%%%;
nlp_tXYC = 0;
tmp_d = + 0.5*n_x*log(2*pi) - 0.5*(C_l0 + C_l1);
for nt=0:n_t-1;
XY_x_ = XY_xt__(:,1+nt);
ignore_Y_x_ = ignore_Y_xt__(:,1+nt);
if (sum(ignore_Y_x_)==0);
nlp_tXYC = nlp_tXYC ...
  + transpose(XY_x_) * ( 0.5*CtCn_xx__ ) * XY_x_ ...
  + tmp_d ...
  ;
else;
if (ignore_Y_x_(1+0)==0) & (ignore_Y_x_(1+1)==1) ; %<-- ignore XY_x_(1+1) ;
nlp_tXYC = nlp_tXYC ...
+ 0.5*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_1) + 0.5*Z2_base_1*XY_x_(1+0).^2; %<-- ignore XY_(1+1). ;
end;%if (ignore_Y_x_(1+0)==0) & (ignore_Y_x_(1+1)==1) ;
if (ignore_Y_x_(1+0)==1) & (ignore_Y_x_(1+1)==0) ; %<-- ignore XY_x_(1+0) ;
nlp_tXYC = nlp_tXYC ...
+ 0.5*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_0) + 0.5*Z2_base_0*XY_x_(1+1).^2; %<-- ignore XY_(1+0). ;
end;%if (ignore_Y_x_(1+0)==1) & (ignore_Y_x_(1+1)==0) ;
end;%else;
end;%for nt=0:n_dt-1;
%%%%;







