function ...
[ ...
 nlp_jXaABYC_integrated_sum ...
,nlp_jXaABYC_sum ...
,X_opt_ixt___ ...
] = ...
SDE3d_nlp_ijXaABYC_strip_2( ...
 parameter ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_ixt___ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);

str_thisfunction = 'SDE3d_nlp_ijXaABYC_strip_2';

if (nargin<1);
disp(sprintf(' %% testing %s',str_thisfunction));
%%%%%%%%;
nf=0;
rng(0);
n_x = 3;
n_i = 2;
n_t_i_ = zeros(n_i,1);
n_j_i_ = zeros(n_i,1);
t_it__ = cell(n_i,1);
index_nt_from_nj_i__ = cell(n_i,1);
ignore_Y_ixj___ = cell(n_i,1);
Y_ixj___ = cell(n_i,1);
for ni=0:n_i-1;
n_t = 8 + ni;
t_t_ = sort(rand(n_t,1));
n_j = ceil(n_t*2);
index_nt_from_nj_ = max(0,min(n_t-1,floor(n_t*rand(n_j,1))));
ignore_Y_xj__ = randn(n_x,n_j)>0.5;
Y_xj__ = randn(n_x,n_j);
n_t_i_(1+ni) = n_t;
t_it__{1+ni} = t_t_;
n_j_i_(1+ni) = n_j;
index_nt_from_nj_i__{1+ni} = index_nt_from_nj_;
Y_ixj___{1+ni} = Y_xj__;
ignore_Y_ixj___{1+ni} = ignore_Y_xj__;
end;%for ni=0:n_i-1;
n_a = 3; a_xa__ = 1*randn(n_x,n_a);
A_xx__ = randn(n_x,n_x);
B_omega_ = 2*pi*rand(3,1) ; B_l0 = 1*randn(); B_l1 = 1*randn(); B_l2 = 1*randn();
C_omega_ = 2*pi*rand(3,1) ; C_l0 = 1*randn(); C_l1 = 1*randn(); C_l2 = 1*randn();
X_ixt___ = [];
parameter = struct('type','parameter');
[ ...
 nlp_jXaABYC_integrated_sum ...
,nlp_jXaABYC_sum ...
,X_opt_ixt___ ...
] = ...
SDE3d_nlp_ijXaABYC_strip_2( ...
 parameter ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_ixt___ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
disp(sprintf(' %% nlp_jXaABYC_integrated_sum: %0.6f',nlp_jXaABYC_integrated_sum));
disp(sprintf(' %% nlp_jXaABYC_sum: %0.6f',nlp_jXaABYC_sum));
%%%%%%%%;
disp('returning'); return;
end;%if (nargin<1);

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_i=[]; end; na=na+1;
if (nargin<1+na); n_t_i_=[]; end; na=na+1;
if (nargin<1+na); t_it__=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); X_ixt___=[]; end; na=na+1;
if (nargin<1+na); n_a=[]; end; na=na+1;
if (nargin<1+na); a_xa__=[]; end; na=na+1;
if (nargin<1+na); A_xx__=[]; end; na=na+1;
if (nargin<1+na); B_omega_=[]; end; na=na+1;
if (nargin<1+na); B_l0=[]; end; na=na+1;
if (nargin<1+na); B_l1=[]; end; na=na+1;
if (nargin<1+na); B_l2=[]; end; na=na+1;
if (nargin<1+na); n_j_i_=[]; end; na=na+1;
if (nargin<1+na); index_nt_from_nj_i__=[]; end; na=na+1;
if (nargin<1+na); ignore_Y_ixj___=[]; end; na=na+1;
if (nargin<1+na); Y_ixj___=[]; end; na=na+1;
if (nargin<1+na); C_omega_=[]; end; na=na+1;
if (nargin<1+na); C_l0=[]; end; na=na+1;
if (nargin<1+na); C_l1=[]; end; na=na+1;
if (nargin<1+na); C_l2=[]; end; na=na+1;

if isempty(X_ixt___);
X_ixt___ = cell(n_i,1);
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
X_ixt___{1+ni} = zeros(n_x,n_t);
end;%for ni=0:n_i-1;
end;%if isempty(X_ixt___);

X_opt_ixt___ = cell(n_i,1);
nlp_jXaABYC_integrated_sum = 0;
nlp_jXaABYC_sum = 0;
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
X_xt__ = X_ixt___{1+ni};
n_j = n_j_i_(1+ni);
index_nt_from_nj_ = index_nt_from_nj_i__{1+ni};
ignore_Y_xj__ = ignore_Y_ixj___{1+ni};
Y_xj__ = Y_ixj___{1+ni};
[ ...
 parameter ...
,nlp_jXaABYC_integrated ...
,X_opt_xt__ ...
,nlp_jXaABYC ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
if isfinite(nlp_jXaABYC_integrated);
nlp_jXaABYC_integrated_sum = nlp_jXaABYC_integrated_sum + nlp_jXaABYC_integrated;
end;%if isfinite(nlp_jXaABYC_integrated);
if isfinite(nlp_jXaABYC);
nlp_jXaABYC_sum = nlp_jXaABYC_sum + nlp_jXaABYC;
end;%if isfinite(nlp_jXaABYC);
X_opt_ixt___{1+ni} = X_opt_xt__;
clear n_t t_t_ X_xt__ n_j index_nt_from_nj_ ignore_Y_xj__ Y_xj__ X_opt_xt__ ;
clear nlp_jXaABYC nlp_jXaABYC_integrated ;
end;%for ni=0:n_i-1;
