function ...
[ ...
 nlp ...
] = ...
SDE3d_nlp_jXYC_eccentricity_2( ...
 n_x ...
,n_j ...
,l0 ...
,l1 ...
,l2 ...
);

na=0;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); n_j=[]; end; na=na+1;
if (nargin<1+na); l0=[]; end; na=na+1;
if (nargin<1+na); l1=[]; end; na=na+1;
if (nargin<1+na); l2=[]; end; na=na+1;

nlp = 0;
nlp = nlp + n_j*0.5*(l0 - l1).^2 + n_j*0.5*(l0 - l2).^2 + n_j*0.5*(l1 - l2).^2 ; %<-- eccentricity penalty. ;
nlp = nlp + n_j*0.5*(l0.^2 + l1.^2 + l2.^2); %<-- magnitude penalty. ;


