function ...
[ ...
 parameter ...
,nlp_jXaABYC_integrated ...
,X_opt_xt__ ...
,nlp_jXaABYC ...
,nlp_dtXaAB ...
,nlp_jXYC ...
,nlp_dtXaAB_dX_xt__ ...
,nlp_dtXaAB_dX_xtxt__ ...
,nlp_jXYC_dX_xt__ ...
,nlp_jXYC_dX_xtxt__ ...
,BtBn_xx__ ...
,CtCn_xx__ ...
,Q_xt__ ...
,P_xt__ ...
,dX_xdt__ ...
,dQ_xdt__ ...
,dP_xdt__ ...
,ZX_xdt__ ...
,ZQ_xdt__ ...
,ZP_xdt__ ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
,Q_xt__ ...
,P_xt__ ...
,dX_xdt__ ...
,dQ_xdt__ ...
,dP_xdt__ ...
,ZX_xdt__ ...
,ZQ_xdt__ ...
,ZP_xdt__ ...
);

str_thisfunction = 'SDE3d_nlp_jXaABYC_2';

if (nargin<1);
disp(sprintf(' %% testing %s',str_thisfunction));
%%%%%%%%;
nf=0;
rng(0);
n_t = 8; t_t_ = sort(rand(n_t,1));
n_x = 3; X_xt__ = randn(n_x,n_t);
n_j = ceil(n_t*2);
index_nt_from_nj_ = max(0,min(n_t-1,floor(n_t*rand(n_j,1))));
ignore_Y_xj__ = randn(n_x,n_j)>0.5;
Y_xj__ = randn(n_x,n_j);
n_a = 2; a_xa__ = 1*randn(n_x,n_a);
A_xx__ = 2*randn(n_x,n_x);
B_omega_ = 2*pi*rand(3,1) ; B_l0 = 1*randn(); B_l1 = 1*randn(); B_l2 = 1*randn();
C_omega_ = 2*pi*rand(3,1) ; C_l0 = 1*randn(); C_l1 = 1*randn(); C_l2 = 1*randn();
parameter = struct('type','parameter');
parameter.flag_verbose = 1;
[ ...
 parameter ...
,nlp_jXaABYC_integrated ...
,X_opt_xt__ ...
,nlp_jXaABYC ...
,nlp_dtXaAB ...
,nlp_jXYC ...
,nlp_dtXaAB_dX_xt__ ...
,nlp_dtXaAB_dX_xtxt__ ...
,nlp_jXYC_dX_xt__ ...
,nlp_jXYC_dX_xtxt__ ...
,BtBn_xx__ ...
,CtCn_xx__ ...
,Q_xt__ ...
,P_xt__ ...
,dX_xdt__ ...
,dQ_xdt__ ...
,dP_xdt__ ...
,ZX_xdt__ ...
,ZQ_xdt__ ...
,ZP_xdt__ ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
disp(sprintf(' %% nlp_jXaABYC_integrated: %f',nlp_jXaABYC_integrated));
disp(sprintf(' %% nlp_jXaABYC: %f',nlp_jXaABYC));
disp(sprintf(' %% nlp_dtXaAB: %f',nlp_dtXaAB));
disp(sprintf(' %% nlp_jXYC: %f',nlp_jXYC));
parameter.flag_verbose=0;
%%%%;
tmp_eps = fnorm(X_xt__)*1e-4;
n_test = 16;
nlp_dtXaAB_dX_emp_l_ = zeros(n_test,1);
nlp_dtXaAB_dX_est_l_ = zeros(n_test,1);
nlp_jXYC_dX_emp_l_ = zeros(n_test,1);
nlp_jXYC_dX_est_l_ = zeros(n_test,1);
for ntest=0:n_test-1;
dX_xt__ = randn(n_x,n_t); dX_xt__ = dX_xt__/fnorm(dX_xt__);
tmp_X_xt__ = X_xt__ + tmp_eps*dX_xt__;
[ ...
 ~ ...
,nlp_jXaABYC_integrated_pos ...
,~ ...
,nlp_jXaABYC_pos ...
,nlp_dtXaAB_pos ...
,nlp_jXYC_pos ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,tmp_X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
tmp_X_xt__ = X_xt__ - tmp_eps*dX_xt__;
[ ...
 ~ ...
,nlp_jXaABYC_integrated_neg ...
,~ ...
,nlp_jXaABYC_neg ...
,nlp_dtXaAB_neg ...
,nlp_jXYC_neg ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,tmp_X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
nlp_dtXaAB_dX_emp_l_(1+ntest) = (nlp_dtXaAB_pos - nlp_dtXaAB_neg)/(2*tmp_eps);
nlp_dtXaAB_dX_est_l_(1+ntest) = + sum(nlp_dtXaAB_dX_xt__ .* dX_xt__,'all') + reshape(X_xt__,[1,n_x*n_t])*nlp_dtXaAB_dX_xtxt__*reshape(dX_xt__,[n_x*n_t,1]);
nlp_jXYC_dX_emp_l_(1+ntest) = (nlp_jXYC_pos - nlp_jXYC_neg)/(2*tmp_eps);
nlp_jXYC_dX_est_l_(1+ntest) = + sum(nlp_jXYC_dX_xt__ .* dX_xt__,'all') + reshape(X_xt__,[1,n_x*n_t])*nlp_jXYC_dX_xtxt__*reshape(dX_xt__,[n_x*n_t,1]);
end;%for ntest=0:n_test-1;
disp(sprintf(' %% nlp_dtXaAB_dX_emp_l_ vs nlp_dtXaAB_dX_est_l_: %0.16f',fnorm(nlp_dtXaAB_dX_emp_l_ - nlp_dtXaAB_dX_est_l_)/fnorm(nlp_dtXaAB_dX_emp_l_)));
disp(sprintf(' %% nlp_jXYC_dX_emp_l_ vs nlp_jXYC_dX_est_l_: %0.16f',fnorm(nlp_jXYC_dX_emp_l_ - nlp_jXYC_dX_est_l_)/fnorm(nlp_jXYC_dX_emp_l_)));
%%%%;
tmp_RHS_xt_ = reshape(nlp_dtXaAB_dX_xt__,[n_x*n_t,1]) + reshape(nlp_jXYC_dX_xt__,[n_x*n_t,1]) ;
tmp_LHS_xtxt__ = nlp_dtXaAB_dX_xtxt__ + nlp_jXYC_dX_xtxt__ ;
tolerance_master = 1e-6;
%X_opt_xt__ = -reshape(pinv(tmp_LHS_xtxt__,tolerance_master)*tmp_RHS_xt_,[n_x,n_t]);
X_opt_xt__ = -reshape(tmp_LHS_xtxt__\tmp_RHS_xt_,[n_x,n_t]);
tmp_eps = fnorm(X_opt_xt__)*1e-4;
n_test = 16;
scan_max = 0.1;
n_scan = 8+1; eps_s_ = scan_max*transpose(linspace(-1,+1,n_scan));
nlp_jXaABYC_integrated_sl__ = zeros(n_scan,n_test);
nlp_jXaABYC_sl__ = zeros(n_scan,n_test);
for ntest=0:n_test-1;
dX_xt__ = randn(n_x,n_t); dX_xt__ = dX_xt__/fnorm(dX_xt__);
for nscan=0:n_scan-1;
tmp_eps = eps_s_(1+nscan);
tmp_X_xt__ = X_opt_xt__ + tmp_eps*fnorm(X_opt_xt__)*dX_xt__;
[ ...
 ~ ...
,nlp_jXaABYC_integrated_sl__(1+nscan,1+ntest) ...
,~ ...
,nlp_jXaABYC_sl__(1+nscan,1+ntest) ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,tmp_X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
end;%for nscan=0:n_scan-1;
end;%for ntest=0:n_test-1;
%%%%;
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,3,1);
plot(nlp_dtXaAB_dX_emp_l_,nlp_dtXaAB_dX_est_l_,'ko');
xlabel('nlp_dtXaAB_dX_emp_l_','Interpreter','none');
ylabel('nlp_dtXaAB_dX_est_l_','Interpreter','none');
title('nlp_dtXaAB','Interpreter','none');
subplot(1,3,2);
plot(nlp_jXYC_dX_emp_l_,nlp_jXYC_dX_est_l_,'ko');
xlabel('nlp_jXYC_dX_emp_l_','Interpreter','none');
ylabel('nlp_jXYC_dX_est_l_','Interpreter','none');
title('nlp_jXYC','Interpreter','none');
subplot(1,3,3);
hold on;
plot(eps_s_,nlp_jXaABYC_sl__,'ko');
plot(eps_s_(1+(n_scan-1)/2),nlp_jXaABYC_sl__(1+(n_scan-1)/2,:),'ko','MarkerFaceColor','r');
hold off;
xlim(scan_max*[-1,+1]); xlabel('scan');
ylabel('nlp_jXaABYC','Interpreter','none');
title('nlp_jXaABYC','Interpreter','none');
%%%%;
%%%%%%%%;
disp('returning'); return;
end;%if (nargin<1);

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_t=[]; end; na=na+1;
if (nargin<1+na); t_t_=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); X_xt__=[]; end; na=na+1;
if (nargin<1+na); n_a=[]; end; na=na+1;
if (nargin<1+na); a_xa__=[]; end; na=na+1;
if (nargin<1+na); A_xx__=[]; end; na=na+1;
if (nargin<1+na); B_omega_=[]; end; na=na+1;
if (nargin<1+na); B_l0=[]; end; na=na+1;
if (nargin<1+na); B_l1=[]; end; na=na+1;
if (nargin<1+na); B_l2=[]; end; na=na+1;
if (nargin<1+na); n_j_=[]; end; na=na+1;
if (nargin<1+na); index_nt_from_nj_=[]; end; na=na+1;
if (nargin<1+na); ignore_Y_xj__=[]; end; na=na+1;
if (nargin<1+na); Y_xj__=[]; end; na=na+1;
if (nargin<1+na); C_omega_=[]; end; na=na+1;
if (nargin<1+na); C_l0=[]; end; na=na+1;
if (nargin<1+na); C_l1=[]; end; na=na+1;
if (nargin<1+na); C_l2=[]; end; na=na+1;
if (nargin<1+na); Q_xt__=[]; end; na=na+1;
if (nargin<1+na); P_xt__=[]; end; na=na+1;
if (nargin<1+na); dX_xdt__=[]; end; na=na+1;
if (nargin<1+na); dQ_xdt__=[]; end; na=na+1;
if (nargin<1+na); dP_xdt__=[]; end; na=na+1;
if (nargin<1+na); ZX_xdt__=[]; end; na=na+1;
if (nargin<1+na); ZQ_xdt__=[]; end; na=na+1;
if (nargin<1+na); ZP_xdt__=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;
if ~isfield(parameter,'tolerance_master'); parameter.tolerance_master = 1e-2; end;
if ~isfield(parameter,'tolerance_dt'); parameter.tolerance_dt = 1e-12; end;
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose = 0; end;
if ~isfield(parameter,'flag_regularize_eccentricity'); parameter.flag_regularize_eccentricity = 0; end;
tolerance_master = parameter.tolerance_master;
tolerance_dt = parameter.tolerance_dt;
flag_verbose = parameter.flag_verbose;
flag_regularize_eccentricity = parameter.flag_regularize_eccentricity;

if (flag_verbose>0); disp(sprintf(' %% [entering %s]',str_thisfunction)); end;

%%%%;
tmp_t = tic();
[ ...
 n_nj_from_nt_ ...
,index_nj_from_nt__ ...
] = ...
SDE_index_nj_from_nt_0( ...
 n_t ...
,n_j ...
,index_nt_from_nj_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% SDE_index_nj_from_nt_0: %0.6fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'SDE_index_nj_from_nt_0',tmp_t,1,max(n_j,n_t));
%%%%;

%%%%;
tmp_t = tic();
[ ...
 nlp_jXaABYC ...
,nlp_dtXaAB ...
,nlp_jXYC ...
,BtBn_xx__ ...
,CtCn_xx__ ...
,Q_xt__ ...
,P_xt__ ...
,dX_xdt__ ...
,dQ_xdt__ ...
,dP_xdt__ ...
,ZX_xdt__ ...
,ZQ_xdt__ ...
,ZP_xdt__ ...
] = ...
SDE3d_nlp_jXaABYC_strip_2( ...
 n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
,Q_xt__ ...
,P_xt__ ...
,dX_xdt__ ...
,dQ_xdt__ ...
,dP_xdt__ ...
,ZX_xdt__ ...
,ZQ_xdt__ ...
,ZP_xdt__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% SDE3d_nlp_jXaABYC_strip_2: %0.6fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'SDE3d_nlp_jXaABYC_strip_2',tmp_t,1,n_x*n_a*n_t);
%%%%;
[ ...
 ~ ...
,BtBn_xx__ ...
] = ...
SDE3d_BtBn_1( ...
 [] ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
);
[ ...
 ~ ...
,CtCn_xx__ ...
] = ...
SDE3d_BtBn_1( ...
 [] ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
%%%%;

%%%%%%%%%%%%%%%%;
if (n_t<=1);
nlp_jXaABYC_integrated = 0;
X_opt_xt__ = zeros(n_x,n_t);
for nt=0:n_t-1;
tmp_index_ = efind(index_nt_from_nj_==nt);
if numel(tmp_index_)> 0;
nj = min(tmp_index_);
X_opt_xt__(:,1+nt) = Y_xj__(:,1+nj);
end;%if numel(tmp_index_)> 0;
end;%for nt=0:n_t-1;
nlp_jXaABYC = 0;
nlp_dtXaAB = 0;
nlp_jXYC = 0;
nlp_dtXaAB_dX_xt__ = sparse(n_x,n_t);
nlp_dtXaAB_dX_xtxt__ = sparse(n_x*n_t,n_x*n_t);
nlp_jXYC_dX_xt__ = sparse(n_x,n_t);
nlp_jXYC_dX_xtxt__ = sparse(n_x*n_t,n_x*n_t);
end;%if (n_t<=1);
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%;
if (n_t> 1);
%%%%%%%%%%%%%%%%;

XY_xj__ = Y_xj__ - X_xt__(:,1+index_nt_from_nj_);

if isempty(ignore_Y_xj__); ignore_Y_xj__ = ~isfinite(Y_xj__); end;%if isempty(ignore_Y_xj__); 
attend_Y_xj__ = ~ignore_Y_xj__;
attend_Y_111_j_ = transpose((transpose(attend_Y_xj__)*[1;1;1] == 3) & (transpose(attend_Y_xj__)*[0;0;0] == 0));
attend_Y_100_j_ = transpose((transpose(attend_Y_xj__)*[1;0;0] == 1) & (transpose(attend_Y_xj__)*[0;1;1] == 0));
attend_Y_110_j_ = transpose((transpose(attend_Y_xj__)*[1;1;0] == 2) & (transpose(attend_Y_xj__)*[0;0;1] == 0));
attend_Y_010_j_ = transpose((transpose(attend_Y_xj__)*[0;1;0] == 1) & (transpose(attend_Y_xj__)*[1;0;1] == 0));
attend_Y_011_j_ = transpose((transpose(attend_Y_xj__)*[0;1;1] == 2) & (transpose(attend_Y_xj__)*[1;0;0] == 0));
attend_Y_001_j_ = transpose((transpose(attend_Y_xj__)*[0;0;1] == 1) & (transpose(attend_Y_xj__)*[1;1;0] == 0));
attend_Y_101_j_ = transpose((transpose(attend_Y_xj__)*[1;0;1] == 2) & (transpose(attend_Y_xj__)*[0;1;0] == 0));
attend_Y_000_j_ = transpose((transpose(attend_Y_xj__)*[0;0;0] == 0) & (transpose(attend_Y_xj__)*[1;1;1] == 0));
n_111 = sum(attend_Y_111_j_);
n_100 = sum(attend_Y_100_j_);
n_110 = sum(attend_Y_110_j_);
n_010 = sum(attend_Y_010_j_);
n_011 = sum(attend_Y_011_j_);
n_001 = sum(attend_Y_001_j_);
n_101 = sum(attend_Y_101_j_);
n_000 = sum(attend_Y_000_j_);
use_Y_111_j_ = efind(attend_Y_111_j_);
use_Y_100_j_ = efind(attend_Y_100_j_);
use_Y_110_j_ = efind(attend_Y_110_j_);
use_Y_010_j_ = efind(attend_Y_010_j_);
use_Y_011_j_ = efind(attend_Y_011_j_);
use_Y_001_j_ = efind(attend_Y_001_j_);
use_Y_101_j_ = efind(attend_Y_101_j_);
use_Y_000_j_ = efind(attend_Y_000_j_);
if (flag_verbose); disp(sprintf(' %% n_j %0.3d n_111 %0.3d n_100 %0.3d n_110 %0.3d n_010 %0.3d n_011 %0.3d n_001 %0.3d n_101 %0.3d n_000 %0.3d',n_j,n_111,n_100,n_110,n_010,n_011,n_001,n_101,n_000)); end;
[ ...
 Z_base_100_ ...
,l2_stretch_100 ...
,Z_base_110__ ...
,l2_stretch_110 ...
,Z_base_010_ ...
,l2_stretch_010 ...
,Z_base_011__ ...
,l2_stretch_011 ...
,Z_base_001_ ...
,l2_stretch_001 ...
,Z_base_101__ ...
,l2_stretch_101 ...
] = ...
SDE3d_missing_3d_integral_helper_1( ...
 C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
d_111 = + 0.5*3*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) ;
d_100 = + 0.5*1*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) + 0.5*log(l2_stretch_100) ;
d_110 = + 0.5*2*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) + 0.5*log(l2_stretch_110) ;
d_010 = + 0.5*1*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) + 0.5*log(l2_stretch_010) ;
d_011 = + 0.5*2*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) + 0.5*log(l2_stretch_011) ;
d_001 = + 0.5*1*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) + 0.5*log(l2_stretch_001) ;
d_101 = + 0.5*2*log(2*pi) - 0.5*(C_l0 + C_l1 + C_l2) + 0.5*log(l2_stretch_101) ;
ZtZn_100__ = zeros(n_x,n_x); ZtZn_100__(1+0,1+0) = transpose(Z_base_100_)*Z_base_100_;
ZtZn_110__ = zeros(n_x,n_x); ZtZn_110__(1+[0,1],1+[0,1]) = transpose(Z_base_110__)*Z_base_110__;
ZtZn_010__ = zeros(n_x,n_x); ZtZn_010__(1+1,1+1) = transpose(Z_base_010_)*Z_base_010_;
ZtZn_011__ = zeros(n_x,n_x); ZtZn_011__(1+[1,2],1+[1,2]) = transpose(Z_base_011__)*Z_base_011__;
ZtZn_001__ = zeros(n_x,n_x); ZtZn_001__(1+2,1+2) = transpose(Z_base_001_)*Z_base_001_;
ZtZn_101__ = zeros(n_x,n_x); ZtZn_101__(1+[0,2],1+[0,2]) = transpose(Z_base_101__)*Z_base_101__;
%%%%%%%%;

%%%%%%%%;
tmp_t = tic();
%%%%%%%%;
nlp_jXYC_dX_xt__ = sparse(n_x,n_t);
tmp_n_nz = 3*n_111 + 1*n_100 + 1*n_010 + 1*n_001 + 2*n_110 + 2*n_011 + 2*n_101;
tmp_index_row_nz_ = zeros(tmp_n_nz,1);
tmp_index_col_nz_ = zeros(tmp_n_nz,1);
tmp_val_nz_ = zeros(tmp_n_nz,1);
tmp_nnz=0;
%%%%;
tmp_CtCn_Y_xj__ = CtCn_xx__*Y_xj__(:,1+use_Y_111_j_);
for nx=0:n_x-1;
tmp_index_row_nz_(1+tmp_nnz+[0:n_111-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_111-1]) = index_nt_from_nj_(1+use_Y_111_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_111-1]) = -tmp_CtCn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_111;
end;%for nx=0:n_x-1;
%%%%;
tmp_ZtZn_Y_xj__ = ZtZn_100__*Y_xj__(:,1+use_Y_100_j_);
nx = 0; tmp_index_row_nz_(1+tmp_nnz+[0:n_100-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_100-1]) = index_nt_from_nj_(1+use_Y_100_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_100-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_100;
%%%%;
tmp_ZtZn_Y_xj__ = ZtZn_010__*Y_xj__(:,1+use_Y_010_j_);
nx = 1; tmp_index_row_nz_(1+tmp_nnz+[0:n_010-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_010-1]) = index_nt_from_nj_(1+use_Y_010_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_010-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_010;
%%%%;
tmp_ZtZn_Y_xj__ = ZtZn_001__*Y_xj__(:,1+use_Y_001_j_);
nx = 2; tmp_index_row_nz_(1+tmp_nnz+[0:n_001-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_001-1]) = index_nt_from_nj_(1+use_Y_001_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_001-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_001;
%%%%;
tmp_ZtZn_Y_xj__ = ZtZn_110__*Y_xj__(:,1+use_Y_110_j_);
nx = 0; tmp_index_row_nz_(1+tmp_nnz+[0:n_110-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_110-1]) = index_nt_from_nj_(1+use_Y_110_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_110-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_110;
nx = 1; tmp_index_row_nz_(1+tmp_nnz+[0:n_110-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_110-1]) = index_nt_from_nj_(1+use_Y_110_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_110-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_110;
%%%%;
tmp_ZtZn_Y_xj__ = ZtZn_011__*Y_xj__(:,1+use_Y_011_j_);
nx = 1; tmp_index_row_nz_(1+tmp_nnz+[0:n_011-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_011-1]) = index_nt_from_nj_(1+use_Y_011_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_011-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_011;
nx = 2; tmp_index_row_nz_(1+tmp_nnz+[0:n_011-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_011-1]) = index_nt_from_nj_(1+use_Y_011_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_011-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_011;
%%%%;
tmp_ZtZn_Y_xj__ = ZtZn_101__*Y_xj__(:,1+use_Y_101_j_);
nx = 0; tmp_index_row_nz_(1+tmp_nnz+[0:n_101-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_101-1]) = index_nt_from_nj_(1+use_Y_101_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_101-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_101;
nx = 2; tmp_index_row_nz_(1+tmp_nnz+[0:n_101-1]) = nx; tmp_index_col_nz_(1+tmp_nnz+[0:n_101-1]) = index_nt_from_nj_(1+use_Y_101_j_);
tmp_val_nz_(1+tmp_nnz+[0:n_101-1]) = -tmp_ZtZn_Y_xj__(1+nx,:); tmp_nnz = tmp_nnz+n_101;
%%%%;
nlp_jXYC_dX_xt__ = sparse(1+tmp_index_row_nz_,1+tmp_index_col_nz_,tmp_val_nz_,n_x,n_t);
%%%%%%%%;
tmp_n_nz = 9*n_111 + 1*n_100 + 1*n_010 + 1*n_001 + 4*n_110 + 4*n_011 + 4*n_101;
tmp_index_row_nz_ = zeros(tmp_n_nz,1);
tmp_index_col_nz_ = zeros(tmp_n_nz,1);
tmp_val_nz_ = zeros(tmp_n_nz,1);
tmp_nnz=0;
%%%%;
for nxA=0:n_x-1;for nxB=0:n_x-1;
tmp_index_row_nz_(1+tmp_nnz+[0:n_111-1]) = nxA+index_nt_from_nj_(1+use_Y_111_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_111-1]) = nxB+index_nt_from_nj_(1+use_Y_111_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_111-1]) = + CtCn_xx__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_111;
end;end;%for nxA=0:n_x-1; for nxB=0:n_x-1;
%%%%;
for nxA=[0];for nxB=[0];
tmp_index_row_nz_(1+tmp_nnz+[0:n_100-1]) = nxA+index_nt_from_nj_(1+use_Y_100_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_100-1]) = nxB+index_nt_from_nj_(1+use_Y_100_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_100-1]) = +ZtZn_100__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_100;
end;end;%for;
%%%%;
for nxA=[1];for nxB=[1];
tmp_index_row_nz_(1+tmp_nnz+[0:n_010-1]) = nxA+index_nt_from_nj_(1+use_Y_010_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_010-1]) = nxB+index_nt_from_nj_(1+use_Y_010_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_010-1]) = +ZtZn_010__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_010;
end;end;%for;
%%%%;
for nxA=[2];for nxB=[2];
tmp_index_row_nz_(1+tmp_nnz+[0:n_001-1]) = nxA+index_nt_from_nj_(1+use_Y_001_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_001-1]) = nxB+index_nt_from_nj_(1+use_Y_001_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_001-1]) = +ZtZn_001__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_001;
end;end;%for;
%%%%;
for nxA=[0,1];for nxB=[0,1];
tmp_index_row_nz_(1+tmp_nnz+[0:n_110-1]) = nxA+index_nt_from_nj_(1+use_Y_110_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_110-1]) = nxB+index_nt_from_nj_(1+use_Y_110_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_110-1]) = +ZtZn_110__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_110;
end;end;%for;
%%%%;
for nxA=[1,2];for nxB=[1,2];
tmp_index_row_nz_(1+tmp_nnz+[0:n_011-1]) = nxA+index_nt_from_nj_(1+use_Y_011_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_011-1]) = nxB+index_nt_from_nj_(1+use_Y_011_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_011-1]) = +ZtZn_011__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_011;
end;end;%for;
%%%%;
for nxA=[0,2];for nxB=[0,2];
tmp_index_row_nz_(1+tmp_nnz+[0:n_101-1]) = nxA+index_nt_from_nj_(1+use_Y_101_j_)*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_101-1]) = nxB+index_nt_from_nj_(1+use_Y_101_j_)*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_101-1]) = +ZtZn_101__(1+nxA,1+nxB); tmp_nnz = tmp_nnz+n_101;
end;end;%for;
%%%%;
nlp_jXYC_dX_xtxt__ = sparse(1+tmp_index_row_nz_,1+tmp_index_col_nz_,tmp_val_nz_,n_x*n_t,n_x*n_t);
%%%%%%%%;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% nlp_jXYC_dX_xtxt__: %0.6fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'nlp_jXYC_dX_xtxt__',tmp_t,1,n_x*n_t);
%%%%%%%%;

%%%%;
dt_dt_ = diff(t_t_); n_dt = numel(dt_dt_);
dt_min = min(dt_dt_);
if (dt_min< tolerance_dt);
disp(sprintf(' %% Warning, dt_min %0.16f below tolerance_dt %0.16f',dt_min,tolerance_dt));
end;%if (dt_min< tolerance_dt);
M_xx__ = BtBn_xx__;
L_xx__ = transpose(A_xx__)*BtBn_xx__;
R_xx__ = BtBn_xx__*A_xx__;
G_xx__ = transpose(A_xx__)*BtBn_xx__*A_xx__;
%%%%;

%%%%;
tmp_t = tic();
%%%%;
Q_pos_xdt__ = Q_xt__(:,2:n_t-0);
Q_pre_xdt__ = Q_xt__(:,1:n_t-1);
MdQ_xdt__ = bsxfun(@rdivide,M_xx__*(-dQ_xdt__),reshape(max(1e-12,dt_dt_),[1,n_dt]));
LQ_xdt__ = L_xx__*(-dQ_xdt__);
RQ_xdt__ = R_xx__*(-Q_pre_xdt__);
GQ_xdt__ = bsxfun(@times,G_xx__*(-Q_pre_xdt__),reshape(max(1e-12,dt_dt_),[1,n_dt]));
nlp_dtXaAB_dX_bot_xt__ = zeros(n_x,n_t);
nlp_dtXaAB_dX_bot_xt__(:,1:n_t-1) = - MdQ_xdt__ - LQ_xdt__ + RQ_xdt__ + GQ_xdt__;
nlp_dtXaAB_dX_top_xt__ = zeros(n_x,n_t);
nlp_dtXaAB_dX_top_xt__(:,2:n_t-0) = + MdQ_xdt__ - RQ_xdt__;
%%%%;
tmp_n_nz = n_dt*2*9;
tmp_index_row_nz_ = zeros(tmp_n_nz,1);
tmp_index_col_nz_ = zeros(tmp_n_nz,1);
tmp_val_nz_ = zeros(tmp_n_nz,1);
tmp_nnz=0;
%%%%;
for nxA=0:n_x-1; for nxB=0:n_x-1;
tmp_index_row_nz_(1+tmp_nnz+[0:n_dt-1]) = nxA+[0:n_dt-1]*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_dt-1]) = nxB+[1:n_dt-0]*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_dt-1]) = - M_xx__(1+nxA,1+nxB)./max(1e-12,dt_dt_) - L_xx__(1+nxA,1+nxB); tmp_nnz = tmp_nnz + n_dt;
end;end;%for nxB=0:n_x-1; for nxA=0:n_x-1;
%%%%;
for nxA=0:n_x-1; for nxB=0:n_x-1;
tmp_index_row_nz_(1+tmp_nnz+[0:n_dt-1]) = nxA+[0:n_dt-1]*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_dt-1]) = nxB+[0:n_dt-1]*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_dt-1]) = + M_xx__(1+nxA,1+nxB)./max(1e-12,dt_dt_) + L_xx__(1+nxA,1+nxB) + R_xx__(1+nxA,1+nxB) + G_xx__(1+nxA,1+nxB).*max(1e-12,dt_dt_); tmp_nnz = tmp_nnz + n_dt;
end;end;%for nxB=0:n_x-1; for nxA=0:n_x-1;
%%%%;
nlp_dtXaAB_dX_bot_xtxt__ = sparse(1+tmp_index_row_nz_,1+tmp_index_col_nz_,tmp_val_nz_,n_x*n_t,n_x*n_t);
%%%%;
tmp_n_nz = n_dt*2*9;
tmp_index_row_nz_ = zeros(tmp_n_nz,1);
tmp_index_col_nz_ = zeros(tmp_n_nz,1);
tmp_val_nz_ = zeros(tmp_n_nz,1);
tmp_nnz=0;
%%%%;
for nxA=0:n_x-1; for nxB=0:n_x-1;
tmp_index_row_nz_(1+tmp_nnz+[0:n_dt-1]) = nxA+[1:n_dt-0]*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_dt-1]) = nxB+[0:n_dt-1]*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_dt-1]) = - M_xx__(1+nxA,1+nxB)./max(1e-12,dt_dt_) - R_xx__(1+nxA,1+nxB); tmp_nnz = tmp_nnz + n_dt;
end;end;%for nxB=0:n_x-1; for nxA=0:n_x-1;
%%%%;
for nxA=0:n_x-1; for nxB=0:n_x-1;
tmp_index_row_nz_(1+tmp_nnz+[0:n_dt-1]) = nxA+[1:n_dt-0]*n_x; tmp_index_col_nz_(1+tmp_nnz+[0:n_dt-1]) = nxB+[1:n_dt-0]*n_x;
tmp_val_nz_(1+tmp_nnz+[0:n_dt-1]) = + M_xx__(1+nxA,1+nxB)./max(1e-12,dt_dt_); tmp_nnz = tmp_nnz + n_dt;
end;end;%for nxA=0:n_x-1; for nxB=0:n_x-1;
%%%%;
nlp_dtXaAB_dX_top_xtxt__ = sparse(1+tmp_index_row_nz_,1+tmp_index_col_nz_,tmp_val_nz_,n_x*n_t,n_x*n_t);
%%%%%%%%;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% nlp_dtXaAB_dX_xtxt__: %0.6fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'nlp_dtXaAB_dX_xtxt__',tmp_t,1,n_x*n_t);
%%%%%%%%;

nlp_dtXaAB_dX_xt__ = nlp_dtXaAB_dX_bot_xt__ + nlp_dtXaAB_dX_top_xt__;
nlp_dtXaAB_dX_xtxt__ = nlp_dtXaAB_dX_bot_xtxt__ + nlp_dtXaAB_dX_top_xtxt__;

%%%%;
tmp_RHS_xt_ = reshape(nlp_dtXaAB_dX_xt__,[n_x*n_t,1]) + reshape(nlp_jXYC_dX_xt__,[n_x*n_t,1]) ;
tmp_LHS_xtxt__ = nlp_dtXaAB_dX_xtxt__ + nlp_jXYC_dX_xtxt__ ;
if n_t< 128;
X_opt_xt__ = -reshape(pinv(full(tmp_LHS_xtxt__),tolerance_master)*tmp_RHS_xt_,[n_x,n_t]);
end;%if n_t< 128;
if n_t>=128;
X_opt_xt__ = -reshape(tmp_LHS_xtxt__\tmp_RHS_xt_,[n_x,n_t]);
end;%if n_t>=128;
tmp_t = tic();
[tmp_LHS_l_xtxt__,tmp_LHS_u_xtxt__,tmp_LHS_t_xtxt__] = lu(tmp_LHS_xtxt__);
tmp_LHS_ldetu = sum(log(abs(diag(tmp_LHS_u_xtxt__))));
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% tmp_LHS_ldetu: %0.6fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'tmp_LHS_ldetu',tmp_t,1,nnz(tmp_LHS_xtxt__));
nlp_jXaABYC_integrated = nlp_dtXaAB + nlp_jXYC - 0.5*n_t*n_x*log(2*pi) + 0.5*tmp_LHS_ldetu; %<-- multidimensional laplace integral. ;
%%%%;

%%%%%%%%%%%%%%%%;
end;%if (n_t> 1);
%%%%%%%%%%%%%%%%;

nlp_jXaABYC_integrated = nlp_jXaABYC_integrated ...
+ flag_regularize_eccentricity* ...
SDE3d_nlp_jXYC_eccentricity_2( ...
 n_x ...
,n_dt ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
);
nlp_jXaABYC_integrated = nlp_jXaABYC_integrated ...
+ flag_regularize_eccentricity* ...
SDE3d_nlp_jXYC_eccentricity_2( ...
 n_x ...
,n_j ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);

if (flag_verbose>0); disp(sprintf(' %% [finished %s]',str_thisfunction)); end;





