function ...
[ ...
 parameter ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_ixt___ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
] = ...
SDE3d_nlp_ijXaABYC_update_2( ...
 parameter ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_ixt___ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);

str_thisfunction = 'SDE3d_nlp_ijXaABYC_update_2';

if (nargin<1);
disp(sprintf(' %% testing %s',str_thisfunction));
%%%%%%%%;
disp(sprintf(' %% see: test_%s.m',str_thisfunction));
%%%%%%%%;
disp('returning'); return;
end;%if (nargin<1);

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_i=[]; end; na=na+1;
if (nargin<1+na); n_t_i_=[]; end; na=na+1;
if (nargin<1+na); t_it__=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); X_ixt___=[]; end; na=na+1;
if (nargin<1+na); n_a=[]; end; na=na+1;
if (nargin<1+na); a_xa__=[]; end; na=na+1;
if (nargin<1+na); A_xx__=[]; end; na=na+1;
if (nargin<1+na); B_omega_=[]; end; na=na+1;
if (nargin<1+na); B_l0=[]; end; na=na+1;
if (nargin<1+na); B_l1=[]; end; na=na+1;
if (nargin<1+na); B_l2=[]; end; na=na+1;
if (nargin<1+na); n_j_i_=[]; end; na=na+1;
if (nargin<1+na); index_nt_from_nj_i__=[]; end; na=na+1;
if (nargin<1+na); ignore_Y_ixj___=[]; end; na=na+1;
if (nargin<1+na); Y_ixj___=[]; end; na=na+1;
if (nargin<1+na); C_omega_=[]; end; na=na+1;
if (nargin<1+na); C_l0=[]; end; na=na+1;
if (nargin<1+na); C_l1=[]; end; na=na+1;
if (nargin<1+na); C_l2=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;
if ~isfield(parameter,'tolerance_master'); parameter.tolerance_master = 1e-2; end;
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose = 0; end;
if ~isfield(parameter,'str_update'); parameter.str_update = 'CtCn_xx__'; end;
if ~isfield(parameter,'flag_regularize_eccentricity'); parameter.flag_regularize_eccentricity = 0; end;
if ~isfield(parameter,'MaxFunEvals_use'); parameter.MaxFunEvals_use = 1024; end;
tolerance_master = parameter.tolerance_master;
flag_verbose = parameter.flag_verbose;
str_update = parameter.str_update;
flag_regularize_eccentricity = parameter.flag_regularize_eccentricity;

if (flag_verbose>0); disp(sprintf(' %% str_update: %s',str_update)); end;

if isempty(X_ixt___);
X_ixt___ = cell(n_i,1);
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
index_nt_from_nj_ = index_nt_from_nj_i__{1+ni};
ignore_Y_xj__ = ignore_Y_ixj___{1+ni};
Y_xj__ = Y_ixj___{1+ni};
X_xt__ = zeros(n_x,n_t);
X_xt__(:,1+index_nt_from_nj_) = 0.5*Y_xj__.*(~ignore_Y_xj__).*( isfinite(Y_xj__));
X_xt__(find(~isfinite(X_xt__))) = 0;
X_ixt___{1+ni} = X_xt__;
clear n_t t_t_ X_xt__ index_nt_from_nj_ ignore_Y_xj__ Y_xj__ ;
end;%for ni=0:n_i-1;
end;%if isempty(X_ixt___);

if isempty(a_xa__); a_xa__ = zeros(n_x,n_a); end;
if isempty(A_xx__); A_xx__ = zeros(n_x,n_x); end;
if isempty(B_omega_); B_omega_ = zeros(n_x,1); end; if isempty(B_l0); B_l0 = 0; end; if isempty(B_l1); B_l1 = 0; end; if isempty(B_l2); B_l2 = 0; end;
if isempty(C_omega_); C_omega_ = zeros(n_x,1); end; if isempty(C_l0); C_l0 = 0; end; if isempty(C_l1); C_l1 = 0; end; if isempty(C_l2); C_l2 = 0; end;

%%%%%%%%%%%%%%%%;
if ~isempty(strfind(str_update,'CtCn_xx__'));
%%%%%%%%%%%%%%%%;
f_nlp = @(w0l0l1l2_) ...
SDE3d_nlp_ijXYC_strip_3( ...
 n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_ixt___ ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,[w0l0l1l2_(1+0);w0l0l1l2_(1+1);w0l0l1l2_(1+2)] ...
,w0l0l1l2_(1+3) ...
,w0l0l1l2_(1+4) ...
,w0l0l1l2_(1+5) ...
) ...
+ flag_regularize_eccentricity* ...
SDE3d_nlp_jXYC_eccentricity_2( ...
 n_x ...
,sum(n_j_i_) ...
,w0l0l1l2_(1+3) ...
,w0l0l1l2_(1+4) ...
,w0l0l1l2_(1+5) ...
);
nlp_ijXYC_pre = f_nlp([C_omega_;C_l0;C_l1;C_l2]);
[w0l0l1l2_opt_,fval_opt] = fminsearch(f_nlp,[C_omega_;C_l0;C_l1;C_l2],optimset('MaxFunEvals',parameter.MaxFunEvals_use));
C_omega_ = [w0l0l1l2_opt_(1+0);w0l0l1l2_opt_(1+1);w0l0l1l2_opt_(1+2)];
C_l0 = w0l0l1l2_opt_(1+3); C_l1 = w0l0l1l2_opt_(1+4); C_l2 = w0l0l1l2_opt_(1+5);
nlp_ijXYC_pos = f_nlp([C_omega_;C_l0;C_l1;C_l2]);
if (flag_verbose>0);
disp(sprintf(' %% C_omega_ [%+0.2f,%+0.2f,%+0.2f] C_l0 %+0.2f C_l1 %+0.2f C_l2 %+0.2f: nlp_ijXYC %0.6f --> %0.6f',C_omega_,C_l0,C_l1,C_l2,nlp_ijXYC_pre,nlp_ijXYC_pos));
end;%if (flag_verbose>0);
parameter.nlp_ijXYC_pre = nlp_ijXYC_pre;
parameter.nlp_ijXYC_pos = nlp_ijXYC_pos;
clear f_nlp ;
%%%%%%%%%%%%%%%%;
end;%if ~isempty(strfind(str_update,'CtCn_xx__'));
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%;
if ~isempty(strfind(str_update,'BtBn_xx__'));
%%%%%%%%%%%%%%%%;
n_dt_i_ = zeros(n_i,1);
dt_idt__ = cell(n_i,1);
ZP_ixdt___ = cell(n_i,1);
%%%%;
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
X_xt__ = X_ixt___{1+ni};
n_dt = n_t-1;
dt_dt_ = diff(t_t_);
[ ...
 ~ ...
,BtBn_xx__ ...
,~ ...
,~ ...
,~ ...
,~ ...
,~ ...
,~ ...
,~ ...
,ZP_xdt__ ...
] = ...
SDE3d_nlp_dtXaAB_strip_1( ...
 n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
);
n_dt_i_(1+ni) = n_dt;
dt_idt__{1+ni} = dt_dt_;
ZP_ixdt___{1+ni} = ZP_xdt__;
clear n_t t_t_ X_xt__ ZP_xdt__;
end;%for ni=0:n_i-1;
%%%%;
f_nlp = @(w0l0l1l2_) ...
SDE3d_nlp_idtZPB_strip_1( ...
 n_i ...
,n_dt_i_ ...
,dt_idt__ ...
,n_x ...
,ZP_ixdt___ ...
,[w0l0l1l2_(1+0);w0l0l1l2_(1+1);w0l0l1l2_(1+2)] ...
,w0l0l1l2_(1+3) ...
,w0l0l1l2_(1+4) ...
,w0l0l1l2_(1+5) ...
) ...
+ flag_regularize_eccentricity* ...
SDE3d_nlp_jXYC_eccentricity_2( ...
 n_x ...
,sum(n_dt_i_) ...
,w0l0l1l2_(1+3) ...
,w0l0l1l2_(1+4) ...
,w0l0l1l2_(1+5) ...
);
nlp_idtZPB_pre = f_nlp([B_omega_;B_l0;B_l1;B_l2]);
[w0l0l1l2_opt_,fval_opt] = fminsearch(f_nlp,[B_omega_;B_l0;B_l1;B_l2],optimset('MaxFunEvals',parameter.MaxFunEvals_use));
B_omega_ = [w0l0l1l2_opt_(1+0);w0l0l1l2_opt_(1+1);w0l0l1l2_opt_(1+2)];
B_l0 = w0l0l1l2_opt_(1+3); B_l1 = w0l0l1l2_opt_(1+4); B_l2 = w0l0l1l2_opt_(1+5);
nlp_idtZPB_pos = f_nlp([B_omega_;B_l0;B_l1;B_l2]);
%%%%%%%%%%%%%%%%;
if (flag_verbose>0);
disp(sprintf(' %% B_omega_ [%+0.2f,%+0.2f,%+0.2f] B_l0 %+0.2f B_l1 %+0.2f B_l2 %+0.2f: nlp_idtZPB %0.6f --> %0.6f',B_omega_,B_l0,B_l1,B_l2,nlp_idtZPB_pre,nlp_idtZPB_pos));
end;%if (flag_verbose>0);
parameter.nlp_idtZPB_pre = nlp_idtZPB_pre;
parameter.nlp_idtZPB_pos = nlp_idtZPB_pos;
clear f_nlp ;
%%%%%%%%%%%%%%%%;
end;%if ~isempty(strfind(str_update,'BtBn_xx__'));
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%;
if ~isempty(strfind(str_update,'a_xa_')) | ~isempty(strfind(str_update,'A_xx__'));
%%%%%%%%%%%%%%%%;
% Note that we actually update a_xa__ and A_xx__ independently ;
% (each is updated assuming that the other is a constant). ;
%%%%%%%%;
nlp_idtXaAB_pre = 0;
nlp_idtXaAB_da_xa__ = zeros(n_x,n_a);
nlp_idtXaAB_da_xaxa____ = zeros(n_x,n_a,n_x,n_a);
nlp_idtXaAB_dA_xx__ = zeros(n_x,n_x);
nlp_idtXaAB_dA_xxxx____ = zeros(n_x,n_x,n_x,n_x);
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
X_xt__ = X_ixt___{1+ni};
[ ...
 parameter ...
,nlp_dtXaAB ...
,BtBn_xx__ ...
,nlp_dtXaAB_0 ...
,nlp_dtXaAB_a ...
,nlp_dtXaAB_da_xa__ ...
,nlp_dtXaAB_da_xaxa____ ...
,nlp_dtXaAB_A ...
,nlp_dtXaAB_dA_xx__ ...
,nlp_dtXaAB_dA_xxxx____ ...
] = ...
SDE3d_nlp_dtXaAB_1( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
);
nlp_idtXaAB_pre = nlp_idtXaAB_pre + nlp_dtXaAB;
nlp_idtXaAB_da_xa__ = nlp_idtXaAB_da_xa__ + nlp_dtXaAB_da_xa__;
nlp_idtXaAB_da_xaxa____ = nlp_idtXaAB_da_xaxa____ + nlp_dtXaAB_da_xaxa____;
nlp_idtXaAB_dA_xx__ = nlp_idtXaAB_dA_xx__ + nlp_dtXaAB_dA_xx__;
nlp_idtXaAB_dA_xxxx____ = nlp_idtXaAB_dA_xxxx____ + nlp_dtXaAB_dA_xxxx____;
clear n_t t_t_ X_xt_ nlp_dtXaAB BtBn_xx__ nlp_dtXaAB_0 nlp_dtXaAB_a nlp_dtXaAB_da_xa__ nlp_dtXaAB_da_xaxa____ nlp_dtXaAB_A nlp_dtXaAB_dA_xx__ nlp_dtXaAB_dA_xxxx____ ;
end;%for ni=0:n_i-1;
a_xa__ = reshape( - pinv(reshape(nlp_idtXaAB_da_xaxa____,[n_x*n_a,n_x*n_a]),tolerance_master) * reshape(nlp_idtXaAB_da_xa__,[n_x*n_a,1]) , [n_x,n_a] );
A_xx__ = reshape( - pinv(reshape(nlp_idtXaAB_dA_xxxx____,[n_x^2,n_x^2]),tolerance_master) * reshape(nlp_idtXaAB_dA_xx__,[n_x^2,1]) , [n_x,n_x] );
clear nlp_idtXaAB_da_xa__ nlp_idtXaAB_da_xaxa____ nlp_idtXaAB_dA_xx__ nlp_idtXaAB_dA_xxxx____ ;
%%%%;
nlp_idtXaAB_pos = 0;
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
X_xt__ = X_ixt___{1+ni};
[ ...
 parameter ...
,nlp_dtXaAB ...
] = ...
SDE3d_nlp_dtXaAB_1( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
);
nlp_idtXaAB_pos = nlp_idtXaAB_pos + nlp_dtXaAB;
clear n_t t_t_ X_xt_ nlp_dtXaAB ;
end;%for ni=0:n_i-1;
%%%%;
parameter.nlp_idtXaAB_pre = nlp_idtXaAB_pre;
parameter.nlp_idtXaAB_pos = nlp_idtXaAB_pos;
%%%%%%%%%%%%%%%%;
end;%if ~isempty(strfind(str_update,'a_xa_')) | ~isempty(strfind(str_update,'A_xx_'));
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%;
if ~isempty(strfind(str_update,'X_xt__'));
%%%%%%%%%%%%%%%%;
nlp_ijXaABYC_integrated_pre=0;
nlp_ijXaABYC_pre = 0;
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
X_xt__ = X_ixt___{1+ni};
n_j = n_j_i_(1+ni);
index_nt_from_nj_ = index_nt_from_nj_i__{1+ni};
ignore_Y_xj__ = ignore_Y_ixj___{1+ni};
Y_xj__ = Y_ixj___{1+ni};
[ ...
 parameter ...
,nlp_jXaABYC_integrated ...
,X_opt_xt__ ...
,nlp_jXaABYC ...
,nlp_dtXaAB ...
,nlp_tXYC ...
,nlp_dtXaAB_dX_xt__ ...
,nlp_dtXaAB_dX_xtxt__ ...
,nlp_tXYC_dX_xt__ ...
,nlp_tXYC_dX_xtxt__ ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
nlp_ijXaABYC_integrated_pre = nlp_ijXaABYC_integrated_pre + nlp_jXaABYC_integrated;
nlp_ijXaABYC_pre = nlp_ijXaABYC_pre + nlp_jXaABYC;
X_ixt___{1+ni} = X_opt_xt__;
clear n_t t_t_ X_xt__ n_j index_nt_from_nj_ ignore_Y_xj__ Y_xj__ X_opt_xt__ ;
clear nlp_jXaABYC nlp_jXaABYC_integrated nlp_dtXaAB nlp_tXYC nlp_dtXaAB_dX_xt__ nlp_dtXaAB_dX_xtxt__ nlp_tXYC_dX_xt__ nlp_tXYC_dX_xtxt__ ;
end;%for ni=0:n_i-1;
%%%%;
nlp_ijXaABYC_integrated_pos = 0;
nlp_ijXaABYC_pos = 0;
for ni=0:n_i-1;
n_t = n_t_i_(1+ni);
t_t_ = t_it__{1+ni};
X_xt__ = X_ixt___{1+ni};
n_j = n_j_i_(1+ni);
index_nt_from_nj_ = index_nt_from_nj_i__{1+ni};
ignore_Y_xj__ = ignore_Y_ixj___{1+ni};
Y_xj__ = Y_ixj___{1+ni};
[ ...
 parameter ...
,nlp_jXaABYC_integrated ...
,X_opt_xt__ ...
,nlp_jXaABYC ...
] = ...
SDE3d_nlp_jXaABYC_2( ...
 parameter ...
,n_t ...
,t_t_ ...
,n_x ...
,X_xt__ ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
nlp_ijXaABYC_integrated_pos = nlp_ijXaABYC_integrated_pos + nlp_jXaABYC_integrated;
nlp_ijXaABYC_pos = nlp_ijXaABYC_pos + nlp_jXaABYC;
clear n_t t_t_ X_xt__ n_j index_nt_from_nj_ ignore_Y_xj__ Y_xj__ X_opt_xt__ ;
clear nlp_jXaABYC nlp_jXaABYC_integrated ;
end;%for ni=0:n_i-1;
%%%%;
parameter.nlp_ijXaABYC_pre = nlp_ijXaABYC_pre;
parameter.nlp_ijXaABYC_pos = nlp_ijXaABYC_pos;
parameter.nlp_ijXaABYC_integrated_pre = nlp_ijXaABYC_integrated_pre;
parameter.nlp_ijXaABYC_integrated_pos = nlp_ijXaABYC_integrated_pos;
%%%%%%%%%%%%%%%%;
end;%if ~isempty(strfind(str_update,'X_xt__'));
%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%;
if ~isempty(strfind(str_update,'simultaneous'));
%%%%%%%%%%%%%%%%;
% a_xa__ = reshape(input_(1 +       0 + 0 + [0:n_x*n_a-1]),[n_x,n_a]) ;
% A_xx__ = reshape(input_(1 + n_x*n_a + 0 + [0:n_x*n_x-1]),[n_x,n_x]) ;
% B_omega_ = input_(1 + n_x*n_a + n_x*n_x + [0,1,2]);
% B_l0    = input_(1 + n_x*n_a + n_x*n_x + 3);
% B_l1    = input_(1 + n_x*n_a + n_x*n_x + 4);
% B_l2    = input_(1 + n_x*n_a + n_x*n_x + 5);
% C_omega_ = input_(1 + n_x*n_a + n_x*n_x + [6,7,8]);
% C_l0    = input_(1 + n_x*n_a + n_x*n_x + 9);
% C_l1    = input_(1 + n_x*n_a + n_x*n_x + 10);
% C_l2    = input_(1 + n_x*n_a + n_x*n_x + 11);
%%%%%%%%;
parameter_quiet = parameter; parameter_quiet.flag_verbose = 0;
f_nlp = @(input_) ...
SDE3d_nlp_ijXaABYC_strip_2( ...
 parameter_quiet ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,[] ...
,n_a ...
,reshape(input_(1 +       0 + 0 + [0:n_x*n_a-1]),[n_x,n_a]) ...
,reshape(input_(1 + n_x*n_a + 0 + [0:n_x*n_x-1]),[n_x,n_x]) ...
,input_(1 + n_x*n_a + n_x*n_x + [0,1,2]) ...
,input_(1 + n_x*n_a + n_x*n_x + 3) ...
,input_(1 + n_x*n_a + n_x*n_x + 4) ...
,input_(1 + n_x*n_a + n_x*n_x + 5) ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,input_(1 + n_x*n_a + n_x*n_x + [6,7,8]) ...
,input_(1 + n_x*n_a + n_x*n_x + 9) ...
,input_(1 + n_x*n_a + n_x*n_x + 10) ...
,input_(1 + n_x*n_a + n_x*n_x + 11) ...
);
input_pre_ = [a_xa__(:);A_xx__(:);B_omega_;B_l0;B_l1;B_l2;C_omega_;C_l0;C_l1;C_l2];
nlp_ijXaABYC_pre = f_nlp(input_pre_);
if (flag_verbose>=1); str_Display = 'iter'; end; if (flag_verbose< 1); str_Display = 'none'; end;
[input_opt_,fval_opt] = fminsearch(f_nlp,input_pre_,optimset('MaxFunEvals',parameter.MaxFunEvals_use,'Display',str_Display));
a_xa__ = reshape(input_opt_(1 +       0 + 0 + [0:n_x*n_a-1]),[n_x,n_a]) ;
A_xx__ = reshape(input_opt_(1 + n_x*n_a + 0 + [0:n_x*n_x-1]),[n_x,n_x]) ;
B_omega_ = input_opt_(1 + n_x*n_a + n_x*n_x + [0,1,2]);
B_l0    = input_opt_(1 + n_x*n_a + n_x*n_x + 3);
B_l1    = input_opt_(1 + n_x*n_a + n_x*n_x + 4);
B_l2    = input_opt_(1 + n_x*n_a + n_x*n_x + 5);
C_omega_ = input_opt_(1 + n_x*n_a + n_x*n_x + [6,7,8]);
C_l0    = input_opt_(1 + n_x*n_a + n_x*n_x + 9);
C_l1    = input_opt_(1 + n_x*n_a + n_x*n_x + 10);
C_l2    = input_opt_(1 + n_x*n_a + n_x*n_x + 11);
nlp_ijXaABYC_pos = fval_opt;
if (flag_verbose>0);
disp(sprintf(' %% a_xa__: ')); disp(a_xa__);
disp(sprintf(' %% A_xx__: ')); disp(A_xx__);
disp(sprintf(' %% B_omega_ [%+0.2f,%+0.2f,%+0.2f] B_l0 %+0.2f B_l1 %+0.2f B_l2 %+0.2f:',B_omega_,B_l0,B_l1,B_l2));
disp(sprintf(' %% C_omega_ [%+0.2f,%+0.2f,%+0.2f] C_l0 %+0.2f C_l1 %+0.2f C_l2 %+0.2f:',C_omega_,C_l0,C_l1,C_l2));
end;%if (flag_verbose>0);
parameter.nlp_ijXaABYC_pre = nlp_ijXaABYC_pre;
parameter.nlp_ijXaABYC_pos = nlp_ijXaABYC_pos;
%%%%;
[ ...
 ~ ...
,~ ...
,X_ixt__ ...
] = ...
SDE3d_nlp_ijXaABYC_strip_2( ...
 parameter_quiet ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,[] ...
,n_a ...
,a_xa__ ...
,A_xx__ ...
,B_omega_ ...
,B_l0 ...
,B_l1 ...
,B_l2 ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_ixj___ ...
,Y_ixj___ ...
,C_omega_ ...
,C_l0 ...
,C_l1 ...
,C_l2 ...
);
%%%%%%%%%%%%%%%%;
end;%if ~isempty(strfind(str_update,'simultaneous'));
%%%%%%%%%%%%%%%%;







