function ...
[ ...
 Q_xt__ ...
] = ...
SDE_Q_ta_strip_0( ...
 n_t ...
,t_t_ ...
,n_x ...
,n_a ...
,a_xa__ ...
);

str_thisfunction = 'SDE_Q_ta_strip_0';

if (nargin<1);
disp(sprintf(' %% testing %s',str_thisfunction));
%%%%%%%%;
rng(1);
tolerance_master = 1e-6;
T_max = 1.0;
n_x = 3;
n_a = 4;
a_xa__ = [ +1.00 , +0.00 , +0.00, +0.00 ; ...
	   +0.00 , +1.00 , +0.00, +0.00 ; ...
	   +0.00 , +0.00 , +1.00, +0.00 ; ...
	   ] ;
n_t = 1024*8;
t_t_ = transpose(linspace(0,T_max,n_t));
Q0_xt__ = [ transpose(t_t_.^0) ; transpose(t_t_.^1) ; transpose(t_t_.^2) ];
[ ...
 Q1_xt__ ...
] = ...
SDE_Q_ta_strip_0( ...
 n_t ...
,t_t_ ...
,n_x ...
,n_a ...
,a_xa__ ...
);
plot(t_t_,Q1_xt__,'k-',t_t_,1.0*ones(n_t,1),'ko',t_t_,t_t_,'ko',t_t_,t_t_.^2,'ko');
xlim([0,T_max]); xlabel('t_t_','Interpreter','none');
ylabel('Q1_xt__','Interpreter','none');
disp(sprintf(' %% Q0_xt__ vs Q1_xt__: %0.16f',fnorm(Q0_xt__-Q1_xt__)/fnorm(Q0_xt__)));
%%%%%%%%;
disp('returning'); return;
end;%if (nargin<1);

na=0;
if (nargin<1+na); n_t=[]; end; na=na+1;
if (nargin<1+na); t_t_=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); n_a=[]; end; na=na+1;
if (nargin<1+na); a_xa__=[]; end; na=na+1;

Q_xt__ = a_xa__*bsxfun(@power,reshape(t_t_,[1,n_t]),reshape(0:n_a-1,[n_a,1]));

