function ...
[ ...
 parameter ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,X_tru_ixt___ ...
,BtBn_tru_xx__ ...
,BtBn_tru_inv_xx__ ...
,CtCn_tru_xx__ ...
,CtCn_tru_inv_xx__ ...
,n_j_i_ ...
,index_nt_from_nj_i__ ...
,ignore_Y_tru_ixj___ ...
,Y_tru_ixj___ ...
,zlim_i2x___ ...
,P_tru_ixt___ ...
] = ...
SDE_generate_data_2_wrap_0( ...
 parameter ...
,n_i ...
,n_x ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
,X_ini_x_ ...
);

str_thisfunction = 'SDE_generate_data_2_wrap_0';

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_i=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); n_a=[]; end; na=na+1;
if (nargin<1+na); a_tru_xa__=[]; end; na=na+1;
if (nargin<1+na); A_tru_xx__=[]; end; na=na+1;
if (nargin<1+na); B_tru_omega=[]; end; na=na+1;
if (nargin<1+na); B_tru_l0=[]; end; na=na+1;
if (nargin<1+na); B_tru_l1=[]; end; na=na+1;
if (nargin<1+na); C_tru_omega=[]; end; na=na+1;
if (nargin<1+na); C_tru_l0=[]; end; na=na+1;
if (nargin<1+na); C_tru_l1=[]; end; na=na+1;
if (nargin<1+na); X_ini_x_=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;
if (~isfield(parameter,'tolerance_master')); parameter.tolerance_master = 1e-2; end;
if (~isfield(parameter,'flag_verbose')); parameter.flag_verbose = 0; end;
if (~isfield(parameter,'flag_disp')); parameter.flag_disp = 0; end;
if (~isfield(parameter,'dt_avg')); parameter.dt_avg = 0.25; end;
if (~isfield(parameter,'flag_discrete_vs_exponential')); parameter.flag_discrete_vs_exponential = 0; end;
if (~isfield(parameter,'T_ini')); parameter.T_ini = 0; end;
if (~isfield(parameter,'T_max')); parameter.T_max = 64; end;
if (~isfield(parameter,'n_j_factor')); parameter.n_j_factor = 1.02; end; %<-- in dolphin-data roughly 0.0175 of the time-steps are of zero-length. ;
if (~isfield(parameter,'ignore_factor')); parameter.ignore_factor = 0.02; end; %<-- in dolphin-data roughly 2\% of observations are missing. ;
if (~isfield(parameter,'rseed')); parameter.rseed = 0; end;
tolerance_master = parameter.tolerance_master;
flag_verbose = parameter.flag_verbose;
flag_disp = parameter.flag_disp; nf=0;
dt_avg = parameter.dt_avg;
flag_discrete_vs_exponential = parameter.flag_discrete_vs_exponential;
T_ini = parameter.T_ini;
T_max = parameter.T_max;
n_j_factor = parameter.n_j_factor;
ignore_factor = parameter.ignore_factor;
rseed = parameter.rseed;

%%%%;
if isempty(B_tru_omega); B_tru_omega = 0; end;
if isempty(B_tru_l0); B_tru_l0 = 0; end;
if isempty(B_tru_l1); B_tru_l1 = 0; end;
[ ...
 ~ ...
,BtBn_tru_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
);
BtBn_tru_inv_xx__ = pinv(BtBn_tru_xx__,tolerance_master);
%%%%;
if isempty(C_tru_omega); C_tru_omega = 0; end;
if isempty(C_tru_l0); C_tru_l0 = 0; end;
if isempty(C_tru_l1); C_tru_l1 = 0; end;
[ ...
 ~ ...
,CtCn_tru_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
);
CtCn_tru_inv_xx__ = pinv(CtCn_tru_xx__,tolerance_master);
%%%%;

if isempty(X_ini_x_); X_ini_x_ = zeros(n_x,1); end;
n_t_i_ = zeros(n_i,1);
t_it__ = cell(n_i,1);
Q_tru_ixt___ = cell(n_i,1);
P_tru_ixt___ = cell(n_i,1);
X_tru_ixt___ = cell(n_i,1);
n_j_i_ = zeros(n_i,1);
index_nt_from_nj_i__ = cell(n_i,1);
ignore_Y_tru_ixj___ = cell(n_i,1);
Y_tru_ixj___ = cell(n_i,1);
%%%%;
parameter_gen = struct('type','parameter');
parameter_gen.dt_avg = dt_avg;
parameter_gen.flag_discrete_vs_exponential = 0;
parameter_gen.T_ini = T_ini;
parameter_gen.T_max = T_max;
parameter_gen.n_j_factor = n_j_factor;
parameter_gen.ignore_factor = ignore_factor;
parameter_gen.rseed_base = rseed;
RX_avg_i_ = zeros(n_i,1);
RY_avg_i_ = zeros(n_i,1);
zlim_i2x___ = zeros(n_i,2,n_x);
for ni=0:n_i-1;
parameter_gen.rseed = ni + n_i*rseed;
[ ...
 parameter_gen ...
,n_t ...
,t_t_ ...
,Q_tru_xt__ ...
,P_tru_xt__ ...
,X_tru_xt__ ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_tru_xj__ ...
,Y_tru_xj__ ...
,RX_avg ...
,RY_avg ...
,zlim_2x__ ...
] = ...
SDE_generate_data_2( ...
 parameter_gen ...
,n_x ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,BtBn_tru_xx__ ...
,BtBn_tru_inv_xx__ ...
,CtCn_tru_xx__ ...
,CtCn_tru_inv_xx__ ...
,X_ini_x_ ...
);
%%%%;
n_t_i_(1+ni) = n_t;
t_it__{1+ni} = t_t_;
Q_tru_ixt___{1+ni} = Q_tru_xt__;
P_tru_ixt___{1+ni} = P_tru_xt__;
X_tru_ixt___{1+ni} = X_tru_xt__;
RX_avg_i_(1+ni) = RX_avg;
n_j_i_(1+ni) = n_j;
index_nt_from_nj_i__{1+ni} = index_nt_from_nj_;
ignore_Y_tru_ixj___{1+ni} = ignore_Y_tru_xj__;
Y_tru_ixj___{1+ni} = Y_tru_xj__;
RY_avg_i_(1+ni) = RY_avg;
zlim_i2x___(1+ni,:,:) = zlim_2x__;
%%%%;
if flag_disp>0;
figure(1+nf);nf=nf+1;clf;figbig;figbeach();
p_row = 2; p_col = 4; np=0;
for pcol=0:p_col-1;
if pcol==0; tmp_t_t_ = t_t_; tmp_W_xt__ = Q_tru_xt__; tmp_str = 'Q_tru_xt__'; end;
if pcol==1; tmp_t_t_ = t_t_; tmp_W_xt__ = P_tru_xt__; tmp_str = 'P_tru_xt__'; end;
if pcol==2; tmp_t_t_ = t_t_; tmp_W_xt__ = X_tru_xt__; tmp_str = 'X_tru_xt__'; end;
if pcol==3; tmp_t_t_ = t_t_(1+index_nt_from_nj_); tmp_W_xt__ = Y_tru_xj__; tmp_str = 'Y_tru_xj__'; end;
subplot(p_row,p_col,1+pcol+0*p_col);
plot(tmp_t_t_,tmp_W_xt__(1,:),'r-',tmp_t_t_,tmp_W_xt__(2,:),'b-');
xlabel('time');ylabel(tmp_str,'Interpreter','none'); xlim([T_ini,T_max]); ylim([min(zlim_2x__(1+0,:)),max(zlim_2x__(1+1,:))])
subplot(p_row,p_col,1+pcol+1*p_col);
s = surfline_0(tmp_W_xt__(1,:),tmp_W_xt__(2,:),tmp_t_t_); set(s,'LineWidth',3);
xlabel(sprintf('%s(1+0,:)',tmp_str),'Interpreter','none'); xlim(zlim_2x__(:,1+0));
ylabel(sprintf('%s(1+1,:)',tmp_str),'Interpreter','none'); ylim(zlim_2x__(:,1+1));
end;%for pcol=0:p_col-1;
sgtitle(sprintf('ni %d',ni),'Interpreter','none');
end;%if flag_disp;
%%%%;
clear n_t t_t_ Q_tru_xt__ P_tru_xt__ X_tru_xt__ n_j index_nt_from_nj_ ignore_Y_tru_xj__ Y_tru_xj__ RX_avg RY_avg ;
%%%%;
end;%for ni=0:n_i-1;

RY_avg = mean(RY_avg_i_);

