function ...
[ ...
 nlp ...
] = ...
SDE_nlp_idtZPB_strip_0( ...
 n_i ...
,n_dt_i_ ...
,dt_idt__ ...
,n_x ...
,ZP_ixdt___ ...
,B_omega ...
,B_l0 ...
,B_l1 ...
);

na=0;
if (nargin<1+na); n_i=[]; end; na=na+1;
if (nargin<1+na); n_dt_i_=[]; end; na=na+1;
if (nargin<1+na); dt_idt__=[]; end; na=na+1;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); ZP_ixdt___=[]; end; na=na+1;
if (nargin<1+na); B_omega=[]; end; na=na+1;
if (nargin<1+na); B_l0=[]; end; na=na+1;
if (nargin<1+na); B_l1=[]; end; na=na+1;

nlp=0;
for ni=0:n_i-1;
n_dt = n_dt_i_(1+ni);
dt_dt_ = dt_idt__{1+ni};
ZP_xdt__ = ZP_ixdt___{1+ni};
if (n_dt>=1);
nlp = nlp + ...
SDE_nlp_dtZPB_strip_0( ...
 n_dt ...
,dt_dt_ ...
,n_x ...
,ZP_xdt__ ...
,B_omega ...
,B_l0 ...
,B_l1 ...
);
end;%if (n_dt>=1);
end;%for ni=0:n_i-1;









