function ...
[ ...
 nlp_jXYC ...
,CtCn_xx__ ...
] = ...
SDE_nlp_jXYC_strip_2( ...
 n_x ...
,n_t ...
,X_xt__ ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega ...
,C_l0 ...
,C_l1 ...
);

if nargin<1;
rng(0);
n_x = 2; n_t = 1024*8;
X_xt__ = randn(n_x,n_t);
n_j = ceil(n_t*2);
%n_j = n_t;
index_nt_from_nj_ = max(0,min(n_t-1,floor(n_t*rand(n_j,1))));
%index_nt_from_nj_ = transpose(0:n_t-1);
ignore_Y_xj__ = randn(n_x,n_j)>0.5;
Y_xj__ = randn(n_x,n_j);
C_omega = randn();
C_l0 = randn();
C_l1 = randn();
tmp_t = tic();
[ ...
 nlp_jXYC ...
,CtCn_xx__ ...
] = ...
SDE_nlp_jXYC_strip_2( ...
 n_x ...
,n_t ...
,X_xt__ ...
,n_j ...
,index_nt_from_nj_ ...
,ignore_Y_xj__ ...
,Y_xj__ ...
,C_omega ...
,C_l0 ...
,C_l1 ...
);
disp(sprintf(' %% nlp_jXYC: %0.6f',nlp_jXYC));
tmp_t = toc(tmp_t); disp(sprintf(' %% SDE_nlp_jXYC_strip_2: %0.6fs',tmp_t));
disp(sprintf(' %% returning')); return;
end;%if nargin<1;

na=0;
if (nargin<1+na); n_x=[]; end; na=na+1;
if (nargin<1+na); n_t=[]; end; na=na+1;
if (nargin<1+na); X_xt__=[]; end; na=na+1;
if (nargin<1+na); n_j=[]; end; na=na+1;
if (nargin<1+na); index_nt_from_nj_=[]; end; na=na+1;
if (nargin<1+na); ignore_Y_xj__=[]; end; na=na+1;
if (nargin<1+na); Y_xj__=[]; end; na=na+1;
if (nargin<1+na); C_omega=[]; end; na=na+1;
if (nargin<1+na); C_l0=[]; end; na=na+1;
if (nargin<1+na); C_l1=[]; end; na=na+1;

XY_xj__ = Y_xj__ - X_xt__(:,1+index_nt_from_nj_);

[ ...
 ~ ...
,CtCn_xx__ ...
] = ...
SDE_BtBn_0( ...
 [] ...
,C_omega ...
,C_l0 ...
,C_l1 ...
);

if isempty(ignore_Y_xj__); ignore_Y_xj__ = ~isfinite(Y_xj__); end;%if isempty(ignore_Y_xj__); 
ignore_Y_sum_j_ = sum(ignore_Y_xj__,1);
use_Y_01_j_ = ~ignore_Y_sum_j_; n_01 = sum(use_Y_01_j_);
use_Y_0_j_ = (ignore_Y_sum_j_ & ~ignore_Y_xj__(1+0,:)); n_0 = sum(use_Y_0_j_);
use_Y_1_j_ = (ignore_Y_sum_j_ & ~ignore_Y_xj__(1+1,:)); n_1 = sum(use_Y_1_j_);
[Z2_base_0,l2_stretch_0] = SDE_missing_2d_integral_helper_0(0,C_omega,C_l0,C_l1); %<-- ignore XY_(1+0) ;
[Z2_base_1,l2_stretch_1] = SDE_missing_2d_integral_helper_0(1,C_omega,C_l0,C_l1); %<-- ignore XY_(1+1) ;
tmp_d_01 = + 0.5*n_x*log(2*pi) - 0.5*(C_l0 + C_l1); %<-- use both. ;
tmp_d_0  = + 0.5*  1*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_1); %<-- ignore 1. ;
tmp_d_1  = + 0.5*  1*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_0); %<-- ignore 0. ;
nlp_jXYC = ...
+ 0.5*sum( (CtCn_xx__*(XY_xj__.*repmat(use_Y_01_j_,[n_x,1]))).*(XY_xj__.*repmat(use_Y_01_j_,[n_x,1])) , 'all' ) + n_01*tmp_d_01 ...
+ 0.5*Z2_base_1*sum(XY_xj__(1+0,:).^2 .* use_Y_0_j_) + n_0*tmp_d_0 ...
+ 0.5*Z2_base_0*sum(XY_xj__(1+1,:).^2 .* use_Y_1_j_) + n_1*tmp_d_1 ...
;

flag_check=0;
if flag_check;
nlp_jXYC_bkp = nlp_jXYC;
index_use_01_j_ = efind(ignore_Y_sum_j_==0); n_01 = numel(index_use_01_j_);
index_use_0_j_  = efind( (ignore_Y_sum_j_==1) & (ignore_Y_xj__(1+1,:)==1) ); n_0 = numel(index_use_0_j_); %<-- use 0 and ignore 1. ;
index_use_1_j_  = efind( (ignore_Y_sum_j_==1) & (ignore_Y_xj__(1+0,:)==1) ); n_1 = numel(index_use_1_j_); %<-- use 1 and ignore 0. ;
nlp_jXYC = 0;
if (n_01> 0);
tmp_d = + 0.5*n_x*log(2*pi) - 0.5*(C_l0 + C_l1);
XY_01_xj__ = XY_xj__(:,1+index_use_01_j_);
nlp_jXYC = nlp_jXYC + 0.5*sum( (CtCn_xx__*XY_01_xj__).*XY_01_xj__ , 'all' ) + n_01*tmp_d;
end;%if (n_01> 0);
if (n_0> 0);
XY_0_j_ = XY_xj__(1+0,1+index_use_0_j_); %<-- use 0. ;
tmp_d = + 0.5*  1*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_1); %<-- ignore 1. ;
nlp_jXYC = nlp_jXYC + 0.5*Z2_base_1*sum(XY_0_j_.^2) + n_0*tmp_d; %<-- ignore 1.; 
end;%if (n_0> 0);
if (n_1> 0);
XY_1_j_ = XY_xj__(1+1,1+index_use_1_j_); %<-- use 1. ;
tmp_d = + 0.5*  1*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_0); %<-- ignore 0. ;
nlp_jXYC = nlp_jXYC + 0.5*Z2_base_0*sum(XY_1_j_.^2) + n_1*tmp_d; %<-- ignore 0. ;
end;%if (n_1> 0);
disp(sprintf(' %% nlp_jXYC_old: %0.6f',nlp_jXYC_bkp));
disp(sprintf(' %% nlp_jXYC_new: %0.6f',nlp_jXYC));
end;%if flag_check;

flag_check=0;
if flag_check;
%%%%;
nlp_jXYC_bkp = nlp_jXYC;
%%%%%%%%;
% vectorize this later. ;
%%%%%%%%;
nlp_jXYC = 0;
tmp_d = + 0.5*n_x*log(2*pi) - 0.5*(C_l0 + C_l1);
for nj=0:n_j-1;
XY_x_ = XY_xj__(:,1+nj);
ignore_Y_x_ = ignore_Y_xj__(:,1+nj);
if (sum(ignore_Y_x_)==0);
nlp_jXYC = nlp_jXYC ...
  + transpose(XY_x_) * ( 0.5*CtCn_xx__ ) * XY_x_ ...
  + tmp_d ...
  ;
else;
if (ignore_Y_x_(1+0)==0) & (ignore_Y_x_(1+1)==1) ; %<-- ignore XY_x_(1+1) ;
nlp_jXYC = nlp_jXYC ...
+ 0.5*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_1) + 0.5*Z2_base_1*XY_x_(1+0).^2; %<-- ignore XY_(1+1). ;
end;%if (ignore_Y_x_(1+0)==0) & (ignore_Y_x_(1+1)==1) ;
if (ignore_Y_x_(1+0)==1) & (ignore_Y_x_(1+1)==0) ; %<-- ignore XY_x_(1+0) ;
nlp_jXYC = nlp_jXYC ...
+ 0.5*log(2*pi) - 0.5*(C_l0 + C_l1) + 0.5*log(l2_stretch_0) + 0.5*Z2_base_0*XY_x_(1+1).^2; %<-- ignore XY_(1+0). ;
end;%if (ignore_Y_x_(1+0)==1) & (ignore_Y_x_(1+1)==0) ;
end;%else;
end;%for nj=0:n_j-1;
%%%%;
disp(sprintf(' %% nlp_jXYC_old: %0.6f',nlp_jXYC_bkp));
disp(sprintf(' %% nlp_jXYC_new: %0.6f',nlp_jXYC));
end;%if flag_check;






