%%%%%%%%;
tolerance_master = 1e-6;
flag_verbose = 1;
flag_disp = flag_verbose; nf=0;
rseed = 1;
%%%%%%%%;

%%%%%%%%;
% generate SDE data for each individual. ;
%%%%%%%%;
n_x = 2; T_ini = 0; T_max = 256; dt_0in = 0.0625;
A_tru_xx__ = [-0.1 , +1.0   ; ...
            -1 , -0.2 ] ;
n_a = 3;
a_tru_xa__ = [ +1.00 , -2.00/T_max , +9.50/T_max.^2   ; ...
           -0.50 , +1.25/T_max , -9.25/T_max.^2 ] ;
B_tru_omega = pi/3;
B_tru_l0 = +1.0;
B_tru_l1 = -0.5;
[ ...
 ~ ...
,BtBn_tru_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
);
C_tru_omega = pi/5;
C_tru_l0 = +0.3;
C_tru_l1 = -0.8;
[ ...
 ~ ...
,CtCn_tru_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
);
BtBn_tru_inv_xx__ = pinv(BtBn_tru_xx__,tolerance_master);
CtCn_tru_inv_xx__ = pinv(CtCn_tru_xx__,tolerance_master);
%%%%%%%%;
n_i = 3; %<-- number of individuals. ;
n_t_i_ = zeros(n_i,1);
t_it__ = cell(n_i,1);
Q_tru_ixt___ = cell(n_i,1);
P_tru_ixt___ = cell(n_i,1);
X_tru_ixt___ = cell(n_i,1);
Y_tru_ixt___ = cell(n_i,1);
ignore_Y_tru_ixt___ = cell(n_i,1);
%%%%;
parameter_gen = struct('type','parameter');
parameter_gen.dt_avg = dt_0in;
parameter_gen.dt_var = 0.0000;
parameter_gen.T_ini = T_ini;
parameter_gen.T_max = T_max;
for ni=0:n_i-1;
parameter_gen.rseed = 1+ni;
[ ...
 parameter_gen ...
,n_t ...
,t_t_ ...
,Q_tru_xt__ ...
,P_tru_xt__ ...
,X_tru_xt__ ...
,Y_tru_xt__ ...
,R_avg ...
] = ...
SDE_generate_data_1( ...
 parameter_gen ...
,n_x ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,BtBn_tru_xx__ ...
,BtBn_tru_inv_xx__ ...
,CtCn_tru_xx__ ...
,CtCn_tru_inv_xx__ ...
);
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figbig;figbeach();
p_row = 2; p_col = 4; np=0;
for pcol=0:p_col-1;
if pcol==0; tmp_W_xt__ = Q_tru_xt__; tmp_str = 'Q_tru_xt__'; end;
if pcol==1; tmp_W_xt__ = P_tru_xt__; tmp_str = 'P_tru_xt__'; end;
if pcol==2; tmp_W_xt__ = X_tru_xt__; tmp_str = 'X_tru_xt__'; end;
if pcol==3; tmp_W_xt__ = Y_tru_xt__; tmp_str = 'Y_tru_xt__'; end;
subplot(p_row,p_col,1+pcol+0*p_col);
plot(t_t_,tmp_W_xt__(1,:),'r-',t_t_,tmp_W_xt__(2,:),'b-');
xlabel('time');ylabel(tmp_str,'Interpreter','none'); xlim([T_ini,T_max]);
subplot(p_row,p_col,1+pcol+1*p_col);
s = surfline_0(tmp_W_xt__(1,:),tmp_W_xt__(2,:),t_t_); set(s,'LineWidth',3);
xlabel(sprintf('%s(1+0,:)',tmp_str),'Interpreter','none');
ylabel(sprintf('%s(1+1,:)',tmp_str),'Interpreter','none');
end;%for pcol=0:p_col-1;
end;%if flag_disp;
%%%%;
n_t_i_(1+ni) = n_t;
t_it__{1+ni} = t_t_;
Q_tru_ixt___{1+ni} = Q_tru_xt__;
P_tru_ixt___{1+ni} = P_tru_xt__;
X_tru_ixt___{1+ni} = X_tru_xt__;
Y_tru_ixt___{1+ni} = Y_tru_xt__;
ignore_Y_tru_ixt___{1+ni} = zeros(n_x,n_t);
clear n_t t_t_ Q_tru_xt__ P_tru_xt__ X_tru_xt__ Y_tru_xt__ R_avg ;
%%%%;
end;%for ni=0:n_i-1;

%%%%%%%%;
% Recover CtCn_xx__. ;
%%%%%%%%;
parameter_est = struct('type','parameter_est');
parameter_est.tolerance_master = tolerance_master;
parameter_est.flag_verbose = flag_verbose;
parameter_est.str_update = 'CtCn_xx__';
[ ...
 parameter_est ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_tru_ixt____ ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
,ignore_Y_tru_ixt____ ...
,Y_tru_ixt____ ...
,C_est_omega ...
,C_est_l0 ...
,C_est_l1 ...
] = ...
PAD_nlp_itXaABYC_update_0( ...
 parameter_est ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_tru_ixt___ ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
,ignore_Y_tru_ixt___ ...
,Y_tru_ixt___ ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
);
%%%%;
[ ...
 ~ ...
,CtCn_est_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,C_est_omega ...
,C_est_l0 ...
,C_est_l1 ...
);
%%%%;
if flag_verbose;
disp(sprintf(' %% nlp_tXYC_pre %0.6f --> nlp_tXYC_pos %0.6f',parameter_est.nlp_tXYC_pre,parameter_est.nlp_tXYC_pos));
disp(sprintf(' %% CtCn_tru_xx__: ')); disp(CtCn_tru_xx__);
disp(sprintf(' %% CtCn_est_xx__: ')); disp(CtCn_est_xx__);
end;%if flag_verbose;
%%%%%%%%;

%%%%%%%%;
% Recover BtBn_xx__. ;
%%%%%%%%;
parameter_est = struct('type','parameter_est');
parameter_est.tolerance_master = tolerance_master;
parameter_est.flag_verbose = flag_verbose;
parameter_est.str_update = 'BtBn_xx__';
[ ...
 parameter_est ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_tru_ixt____ ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,B_est_omega ...
,B_est_l0 ...
,B_est_l1 ...
,ignore_Y_tru_ixt____ ...
,Y_tru_ixt____ ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
] = ...
PAD_nlp_itXaABYC_update_0( ...
 parameter_est ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_tru_ixt___ ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
,ignore_Y_tru_ixt___ ...
,Y_tru_ixt___ ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
);
%%%%;
[ ...
 ~ ...
,BtBn_est_xx__ ...
] = ...
PAD_BtBn_0( ...
 [] ...
,B_est_omega ...
,B_est_l0 ...
,B_est_l1 ...
);
%%%%;
if flag_verbose;
disp(sprintf(' %% nlp_dtZPB_pre %0.6f --> nlp_dtZPB_pos %0.6f',parameter_est.nlp_dtZPB_pre,parameter_est.nlp_dtZPB_pos));
disp(sprintf(' %% BtBn_tru_xx__: ')); disp(BtBn_tru_xx__);
disp(sprintf(' %% BtBn_est_xx__: ')); disp(BtBn_est_xx__);
end;%if flag_verbose;
%%%%%%%%;

%%%%%%%%;
% Recover a_xa__ and A_xx__. ;
%%%%%%%%;
parameter_est = struct('type','parameter_est');
parameter_est.tolerance_master = tolerance_master;
parameter_est.flag_verbose = flag_verbose-1;
parameter_est.str_update = 'A_xx__';
[ ...
 parameter_est ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_tru_ixt____ ...
,n_a ...
,a_est_xa__ ...
,A_est_xx__ ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
,ignore_Y_tru_ixt____ ...
,Y_tru_ixt____ ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
] = ...
PAD_nlp_itXaABYC_update_0( ...
 parameter_est ...
,n_i ...
,n_t_i_ ...
,t_it__ ...
,n_x ...
,X_tru_ixt___ ...
,n_a ...
,a_tru_xa__ ...
,A_tru_xx__ ...
,B_tru_omega ...
,B_tru_l0 ...
,B_tru_l1 ...
,ignore_Y_tru_ixt___ ...
,Y_tru_ixt___ ...
,C_tru_omega ...
,C_tru_l0 ...
,C_tru_l1 ...
);
%%%%;

