function ...
str_infix ...
= ...
test_dolphin_infix_0( ...
 dt_avg ...
,n_i ...
,n_j_factor ...
,ignore_factor ...
,T_ini ...
,T_max ...
,B_log_amplitude ...
,C_log_amplitude ...
,X_log_amplitude ...
,MaxFunEvals_use_simultaneous ...
,flag_regularize_eccentricity_simultaneous ...
,rseed ...
);

str_dt_avg = sprintf('dt%.4d',floor(1000*dt_avg));
str_n_i = sprintf('i%.3d',n_i);
str_n_j_factor = sprintf('j%.3d',floor(100*n_j_factor));
str_ignore_factor = sprintf('i%.3d',floor(100*ignore_factor));
str_T_max = sprintf('T%.3d',floor(10*T_max));
str_B_log_amplitude = sprintf('B%c%.1d','0' + (B_log_amplitude>0)*('p'-'0') + (B_log_amplitude<0)*('n'-'0'),round(abs(B_log_amplitude)));
str_C_log_amplitude = sprintf('C%c%.1d','0' + (C_log_amplitude>0)*('p'-'0') + (C_log_amplitude<0)*('n'-'0'),round(abs(C_log_amplitude)));
str_X_log_amplitude = sprintf('X%c%.1d','0' + (X_log_amplitude>0)*('p'-'0') + (X_log_amplitude<0)*('n'-'0'),round(abs(X_log_amplitude)));
str_MaxFunEvals_use_simultaneous = sprintf('M%.3d',MaxFunEvals_use_simultaneous);
str_flag_regularize_eccentricity_simultaneous = sprintf('e%d',flag_regularize_eccentricity_simultaneous);
str_rseed = sprintf('r%d',rseed);
str_infix = sprintf('%s%s%s%s%s%s%s%s%s%s%s' ...
,str_dt_avg ...
,str_n_i ...
,str_n_j_factor ...
,str_ignore_factor ...
,str_T_max ...
,str_B_log_amplitude ...
,str_C_log_amplitude ...
,str_X_log_amplitude ...
,str_MaxFunEvals_use_simultaneous ...
,str_flag_regularize_eccentricity_simultaneous ...
,str_rseed ...
);
